name: Build Image On Release

on:
  release:
    types: [published]
  pull_request:

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v6
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "nomacs"
      release_type: "github_tag"
      release_url: "https://api.github.com/repos/nomacs/nomacs"
      release_name: ""
      target-arch: "all"
    secrets:
      scarf_token: ${{ secrets.SCARF_TOKEN }}
