name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/check-and-release.yml@v7.0.3
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "nomacs"
      release_type: "github_commit"
      release_url: "https://api.github.com/repos/nomacs/nomacs/commits/master"
    secrets:
      repo_release_token: ${{ secrets.repo_release_token }}
